(defvar promql-mode--functions
  (let ((tmp-hash-table (make-hash-table :test 'equal)))
    (puthash "count_over_time" '("v range-vector") tmp-hash-table)
    (puthash "drop_common_labels" '("instant-vector") tmp-hash-table)
    (puthash "predict_linear" '("v range-vector" "t scalar") tmp-hash-table)
    (puthash "histogram_quantile" '("φ float" "v instant-vector") tmp-hash-table)
    (puthash "count_scalar" '("v instant-vector") tmp-hash-table)
    (puthash "days_in_month" '("v instant-vector") tmp-hash-table)
    (puthash "label_replace" '("v range-vector") tmp-hash-table)
    (puthash "increase" '("v range-vector") tmp-hash-table)
    (puthash "clamp_min" '("v instant-vector" "min scalar") tmp-hash-table)
    (puthash "exp" '("v instant-vector") tmp-hash-table)
    (puthash "stddev_over_time" '("v range-vector") tmp-hash-table)
    (puthash "scalar" '("v instant-vector" "to_nearest=1 scalar") tmp-hash-table)
    (puthash "log10" '("v instant-vector") tmp-hash-table)
    (puthash "vector" '("s scalar") tmp-hash-table)
    (puthash "absent" '("v instant-vector") tmp-hash-table)
    (puthash "sort" '("v instant-vector") tmp-hash-table)
    (puthash "max_over_time" '("v range-vector") tmp-hash-table)
    (puthash "sum_over_time" '("v range-vector") tmp-hash-table)
    (puthash "log2" '("v instant-vector") tmp-hash-table)
    (puthash "min_over_time" '("v range-vector") tmp-hash-table)
    (puthash "abs" '("v instant-vector") tmp-hash-table)
    (puthash "irate" '("v range-vector") tmp-hash-table)
    (puthash "floor" '("v instant-vector") tmp-hash-table)
    (puthash "avg_over_time" '("v range-vector") tmp-hash-table)
    (puthash "resets" '("v range-vector") tmp-hash-table)
    (puthash "sort_desc" '("v instant-vector") tmp-hash-table)
    (puthash "deriv" '("v range-vector") tmp-hash-table)
    (puthash "stdvar_over_time" '("v range-vector") tmp-hash-table)
    (puthash "ceil" '("v instant-vector") tmp-hash-table)
    (puthash "sqrt" '("v instant-vector") tmp-hash-table)
    (puthash "hour" '("v range-vector" "sf scalar" "tf scalar") tmp-hash-table)
    (puthash "changes" '("v instant-vector") tmp-hash-table)
    (puthash "rate" '("v range-vector") tmp-hash-table)
    (puthash "day_of_week" '("v instant-vector") tmp-hash-table)
    (puthash "quantile_over_time" '("s scalar" "v range-vector") tmp-hash-table)
    (puthash "delta" '("v range-vector") tmp-hash-table)
    (puthash "idelta" '("v range-vector") tmp-hash-table)
    (puthash "holt_winters" '("v range-vector" "sf scalar" "tf scalar") tmp-hash-table)
    (puthash "time" '("v instant-vector") tmp-hash-table)
    (puthash "day_of_month" '("v instant-vector") tmp-hash-table)
    (puthash "ln" '("v instant-vector") tmp-hash-table)
    (puthash "clamp_max" '("v instant-vector" "max scalar") tmp-hash-table)
    (puthash "month" '("v instant-vector") tmp-hash-table)
    (puthash "round" '("v instant-vector" "to_nearest=1 scalar") tmp-hash-table)
    tmp-hash-table))

(provide 'promql-mode-words)
